"""add users table and nullable tenant fks

Revision ID: 3b59140ce1ca
Revises: 6f42e4cd4ab0
Create Date: 2026-08-01 21:49:17.782872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '3b59140ce1ca'
down_revision: Union[str, Sequence[str], None] = '6f42e4cd4ab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Pre-auth demo/test data has no owning user and can't be attributed to
    # anyone - drop it rather than inventing a fake account to backfill onto.
    # Merchants stay (global name-lookup table, not tenant data).
    op.execute("DELETE FROM transactions")
    op.execute("DELETE FROM subscriptions")
    op.execute("DELETE FROM plaid_items")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('plaid_items', sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True))
    op.create_foreign_key(None, 'plaid_items', 'users', ['user_id'], ['id'])
    op.add_column('subscriptions', sa.Column('plaid_item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subscriptions', 'plaid_items', ['plaid_item_id'], ['id'])
    op.add_column('transactions', sa.Column('plaid_item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'plaid_items', ['plaid_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'plaid_item_id')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'plaid_item_id')
    op.drop_constraint(None, 'plaid_items', type_='foreignkey')
    op.drop_column('plaid_items', 'user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
