"""add merchants normalized_name

Revision ID: 630ed5da6a59
Revises: 2d2d3d64d3cb
Create Date: 2026-07-30 15:45:35.009403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '630ed5da6a59'
down_revision: Union[str, Sequence[str], None] = '2d2d3d64d3cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('normalized_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'normalized_name')
    # ### end Alembic commands ###
