"""tighten tenant fk columns to not null and add indexes

Revision ID: 63998741dce1
Revises: 3b59140ce1ca
Create Date: 2026-08-01 22:18:27.146347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63998741dce1'
down_revision: Union[str, Sequence[str], None] = '3b59140ce1ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plaid_items', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_plaid_items_user_id'), 'plaid_items', ['user_id'], unique=False)
    op.alter_column('subscriptions', 'plaid_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_subscriptions_plaid_item_id'), 'subscriptions', ['plaid_item_id'], unique=False)
    op.alter_column('transactions', 'plaid_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_transactions_plaid_item_id'), 'transactions', ['plaid_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_plaid_item_id'), table_name='transactions')
    op.alter_column('transactions', 'plaid_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_subscriptions_plaid_item_id'), table_name='subscriptions')
    op.alter_column('subscriptions', 'plaid_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_plaid_items_user_id'), table_name='plaid_items')
    op.alter_column('plaid_items', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
