"""add forecasting and drift scoring columns

Revision ID: 6f42e4cd4ab0
Revises: 824387bb6f9e
Create Date: 2026-07-31 14:32:49.151473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f42e4cd4ab0'
down_revision: Union[str, Sequence[str], None] = '824387bb6f9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('forecast_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('subscriptions', sa.Column('forecast_date', sa.Date(), nullable=True))
    op.add_column('transactions', sa.Column('expected_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('deviation_pct', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('is_drift', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_drift')
    op.drop_column('transactions', 'deviation_pct')
    op.drop_column('transactions', 'expected_amount')
    op.drop_column('subscriptions', 'forecast_date')
    op.drop_column('subscriptions', 'forecast_amount')
    # ### end Alembic commands ###
