"""add transactions subscription_id

Revision ID: 824387bb6f9e
Revises: 630ed5da6a59
Create Date: 2026-07-30 15:46:33.389253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '824387bb6f9e'
down_revision: Union[str, Sequence[str], None] = '630ed5da6a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('subscription_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'subscriptions', ['subscription_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'subscription_id')
    # ### end Alembic commands ###
